FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY analytics_service /app/analytics_service

EXPOSE 8001
CMD ["uvicorn", "analytics_service.main:app", "--host", "0.0.0.0", "--port", "8001"]

